name: ci-package-manager

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    ci-package-manager:
        # Skip on Release Please PRs
        # https://github.com/eslint/rewrite/issues/366
        if: >-
            !(github.event_name == 'pull_request' && github.event.pull_request.user.login == 'eslintbot' && contains(github.event.pull_request.title, 'chore: release'))
        uses: eslint/workflows/.github/workflows/ci-package-manager.yml@main
